[T] (quests) botania
ShaBaiTianCN/Andromeda-Automation pull request #11
Opened 2022-08-24 02:00 UTC by luo-2233

Co-authored-by: 海福 <18917570841@163.com>
Co-authored-by: 咸鱼啊喵丶 <74285624+XianYuAmiao@users.noreply.github.com>

2022-08-24 03:30 UTC, Cactusstudent requested changes
我恨不得给这PR打100个Request Changes
没改完，还有成吨的错误和标点

Machine Translation！！！

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["魔力发射器（红石）是你早期运输魔力的方法。只需用森林法杖右键点击它，然后在你想让魔力到达的地方（如符文祭坛或魔力池）进行右键移动。它只从生成花或其他法力发送那里获得魔力。你可以用任何颜色的羊毛右键点击它，可以让其声音消失。"]
```suggestion
			description: ["魔力发射器是你早期传输魔力的方法。只需用森林法杖右键点击它，然后在你想让魔力到达的地方（如符文祭坛或魔力池）点击右键，即可传输魔力。它只从产能花或其他魔力传输方式那里获得魔力。如果它过于吵闹，你可以用任何颜色的羊毛右键点击它，可以让其声音消失。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["将5块活石和5块青金石摆成正方形格子图案。将泰拉凝聚板放在上面的中心位置。在它上面放上火花以获得魔力，在板上放上一个魔力钢锭、一个魔力钻石和一个魔力珍珠，最后你会得到一个泰拉钢锭!"]
```suggestion
			description: ["将5块活石和4块青金石摆成正方形格子图案。将泰拉凝聚板放在上面的中心位置。在它上面放上火花以获得魔力，在泰拉凝聚板上放上一个魔力钢锭、一个魔力钻石和一个魔力珍珠，最后你会得到一个泰拉钢锭!"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["魔力分配器是一个有用的装置，可以将射入它的魔力均匀地分给任何相邻的魔力池。"]
```suggestion
			description: ["魔力分配器是一个有用的装置，可以将注入它的魔力均匀地分给任何相邻的魔力池。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["透镜是非常有用的。你可以用它们以许多不同的方式改变一个脉冲。有了史莱姆球，你还可以在工作台中把任何两个透镜组合在一起。"]
```suggestion
			description: ["透镜是非常有用的。你可以用它们以许多不同的方式改变一个脉冲。有了黏液球，你还可以在工作台中把任何两个透镜组合在一起。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["这块板可以放在魔力池下面。它允许魔力力池接受魔力，即使它已经满了，它也只是将其作废。在自动化情况下很有用，你不需要担心设置溢出缓冲区的问题。"]
```suggestion
			description: ["这个方块可以放在魔力池下面。它允许魔力池接受魔力，即使它已经满了，它也只是将其作废。在自动化情况下很有用，你不需要担心设置溢出缓冲区的问题。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["魔源服将大大增加你使用任何魔力消耗物品时的效率。"]
```suggestion
			description: ["魔源套装将大大增加你使用任何魔力消耗物品时的效率。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["当你开采普通石头时，源质钢镐会使它们失效，但不会使矿石失效。这可以与泰拉钢镐结合起来，使其具有这种特性，但这是不可逆转的。"]
```suggestion
			description: ["当你开采普通石头时，源质钢镐会清除他们，但不会使矿石失效。这可以与泰拉钢镐结合起来，使其具有这种特性，但这是不可逆转的。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["将普通的下届岩变成任何在下届岩产生的矿石。"]
```suggestion
			description: ["将普通的下界岩变成任何在下界岩产生的矿石。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["让非玩家实体停在他们的轨道上。使他们无法移动。"]
```suggestion
			description: ["让非玩家实体停在他们的路径上，使他们无法移动。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["这朵花会在相当大的范围内拾取任何物品，并将它们放入邻近的库存方块。你可以用包含你想过滤的物品的物品框架来过滤哪些物品被放入库存方块。"]
```suggestion
			description: ["这朵花会在相当大的范围内拾取任何物品，并将它们放入邻近的容器中。可以过滤放置在物品展示框的物品，所以，你可以将想过滤的物品放在其中。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["导致附近的敌对怪物互相厮杀。"]
```suggestion
			description: ["让附近的敌对怪物互相厮杀。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["将沙子转化为粘土。"]
```suggestion
			description: ["将沙子转化为黏土。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["消耗魔力炸毁5格内的所有东西包括你。"]
```suggestion
			description: ["消耗魔力炸毁5格内的所有东西，同时包括你。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["消耗魔力将你使你飞向高空。如果你在使用它之后一路摔落，你不会受到摔落伤害。"]
```suggestion
			description: ["消耗魔力使你飞向高空。如果你在使用它之后从高处一路掉落，你不会受到摔落伤害。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["用魔力召唤出一个土方块。"]
```suggestion
			description: ["用魔力召唤出一块泥土"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			title: "草种子"
```suggestion
			title: "草种"
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["有了物品框架，你可以把一个物品框架与一个物品放在一起。当对该物品的请求被处理，而网络中没有该物品时，它将发出一个红石。很适合相互依赖的自动制作装置。"]
```suggestion
			description: ["有了物品展示框，你可以把一个物品展示框与一个物品放在一起。当对该物品的请求被处理，而网络中没有该物品时，它将发出一个红石信号。很适合相互依赖的自动制作装置。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["其工作方式类似于多媒体网络中的漏斗。使用一个物品框架，你可以指定什么物品要从里面出来。转动框架中的物品来指定数量。它是二进制的，所以2、4、8、16、32、64。物品会在它上面跳出来，如果它下面有一个库存方块，则会存储在库存方块中。"]
```suggestion
			description: ["其工作方式类似于多媒体网络中的漏斗。使用一个物品展示框，你可以指定什么物品要从里面出来。转动框架中的物品来指定数量。它是成倍增加的，所以2、4、8、16、32、64。物品会在它上面跳出来，如果它下面有一个库存方块，则会存储在库存方块中。"]
```

2022-08-24 03:30 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["精灵传送门的制作类似于下届传送门，只是采用了3x3的模式。你把精灵门核心放在中间的底座上，三个微光活木将在每面墙的焦点中心，其余的是由活木制成。它需要两个魔力池，上面有自然水晶。要激活传送门，确保池子里有足够的魔力，然后用森林法杖右击传送门。这个传送门可以用来获得高级物品以换取其他物品。它确实需要魔力来维持，所以要确保有自然水晶和它附近的魔力池中的魔力不会被完
```suggestion
			description: ["精灵传送门的制作类似于下界传送门，只是采用了3x3的模式。你把精灵门核心放在中间的底座上，三个微光活木将在每面墙的焦点中心，其余的是由活木制成。它需要两个魔力池，上面有自然水晶。要激活传送门，确保池子里有足够的魔力，然后用森林法杖右击传送门。这个传送门可以用来获得高级物品以换取其他物品。它确实需要魔力来维持，所以要确保有自然水晶和它附近的魔力池中的魔力不会被完全耗尽。"]
```

2022-08-25 04:53 UTC, luo-2233 reviewed
应该就这些了。。应该。。吧

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["魔力发射器（红石）是你早期运输魔力的方法。只需用森林法杖右键点击它，然后在你想让魔力到达的地方（如符文祭坛或魔力池）进行右键移动。它只从生成花或其他法力发送那里获得魔力。你可以用任何颜色的羊毛右键点击它，可以让其声音消失。"]
```suggestion
			description: ["魔力发射器（红石）是你早期运输魔力的方法。只需用森林法杖右键点击它，然后在你想让魔力到达的地方（如符文祭坛或魔力池）进行右键移动。它只从生成花或其他魔力脉冲那里获得魔力。你可以用任何颜色的羊毛右键点击它，可以让其声音消失。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["将5块活石和5块青金石摆成正方形格子图案。将泰拉凝聚板放在上面的中心位置。在它上面放上火花以获得魔力，在板上放上一个魔力钢锭、一个魔力钻石和一个魔力珍珠，最后你会得到一个泰拉钢锭!"]
```suggestion
			description: ["将5块活石和4块青金石摆成正方形格子图案。将泰拉凝聚板放在上面的中心位置。在它上面放上火花以获得魔力，在板上放上一个魔力钢锭、一个魔力钻石和一个魔力珍珠，最后你会得到一个泰拉钢锭!"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["火花是非常有用的高级魔力传输物品。它们可以用来从魔力池中转移魔力，这与魔力发射器不同。它们有多种可制作的增强器，以实现不同的模式。"]
```suggestion
			description: ["火花是非常有用的高级魔力传输物品。它们可以用来从魔力池中转移魔力，这与魔力发射器不同。它们有多种可制作的升级，以实现不同的模式。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["透镜是非常有用的。你可以用它们以许多不同的方式改变一个脉冲。有了史莱姆球，你还可以在工作台中把任何两个透镜组合在一起。"]
```suggestion
			description: ["透镜是非常有用的。你可以用它们以许多不同的方式改变一个脉冲。有了粘液球，你还可以在工作台中把任何两个透镜组合在一起。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["对魔力脉冲有引力。甚至可以使它们进入围绕它的轨道。."]
```suggestion
			description: ["对魔力脉冲有引力。甚至可以使它们进入围绕它的轨道。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["增加小精灵带着盔甲出生的机会，并给他们一个BUFF。"]
```suggestion
			description: ["增加盔甲召唤小精灵的概率，并给予目标一个BUFF。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["概率性斩杀一些怪物和玩家。概率随着掠夺的增加而增加。"]
```suggestion
			description: ["概率性斩首一些怪物和玩家。概率随着时运等级的增加而增加。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["你可以用任何常规的神秘花来制作这些花。将这些花中的一朵与工作台中的功能花或生成花结合起来，就可以制作出该花的浮空版本。"]
```suggestion
			description: ["你可以用任何常规的神秘花来制作这些花。将这些花中的一朵与工作台中的功能花或产能花结合起来，就可以制作出该花的浮空版本。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["当他们在它的范围内时，防止来自玩家的放大作用。如果这将破坏自动化设置，则很有帮助。"]
```suggestion
			description: ["在它的范围内，阻止来自玩家的吸引效果。如果这将破坏自动化设置，则很有帮助。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["将普通的下界岩变成任何在下界岩产生的矿石。"]
```suggestion
			description: ["将普通的下界岩变成任何在下界岩生成的矿石。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["生成地牢战利品！其形式是：受保护的怪物，死亡时各掉落一件物品。"]
```suggestion
			description: ["生成地牢战利品！其形式是：保护它的怪物，死亡时各掉落一件物品。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["使用魔力创建一个临时的彩虹桥。也可用于在工作台中创建彩虹方块。"]
```suggestion
			description: ["使用魔力创建一个临时的彩虹桥。也可用于在工作台中制作彩虹桥方块。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["可以通过简单的右击自动融化任何可烹饪的方块。"]
```suggestion
			description: ["可以通过简单的右击自动熔炼任何可熔炼的方块。"]
```

2022-08-25 04:53 UTC, luo-2233 commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["多媒体网络的接口。它没有gui，而是使用Minecraft中的聊天栏工作。只要告诉它你想要什么，它就会吐出来。你可以把它用于你手中的东西，你可以使用通配符选择器，如\"and\"\"*\"来获得多个东西。这很不正规，但一旦你掌握了它的窍门就会很有趣。"]
```suggestion
			description: ["多媒体网络的接口。它没有gui，而是使用Minecraft中的聊天栏工作。只要告诉它你想要什么，它就会吐出来。你可以把它用于你手中的东西，你可以使用通配符选择器，如\"and\"\"*\"来获得多个东西。这很不符合常理，但一旦你掌握了它的窍门就会很有趣。"]
```

2022-08-25 05:21 UTC, Cactusstudent reviewed
问题差不多了，下一遍看完再打Approve吧

2022-08-25 05:21 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["这朵花可以将进入它半径内的怪物紧紧抓住，防止他们走掉。"]
```suggestion
			description: ["这朵花可以将接近它的怪物紧紧抓住，防止它们走掉。"]
```

2022-08-25 05:21 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["将物品传送到12个格内的指定地点。用森林法杖配置。"]
```suggestion
			description: ["将物品传送到12个方块内的指定地点。用森林法杖配置。"]
```

2022-08-25 05:21 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["将把石头变成任何在普通石头中生成的矿石。它也适用于深板岩。"]
```suggestion
			description: ["将把石头变成任何以石头为基底生成的矿石，也适用于深板岩。"]
```

2022-08-25 05:21 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["这种花可以用来加快附近任何农作物、树木或其他可生长的东西的生长速度。"]
```suggestion
			description: ["这种花可以用来加速附近任何农作物、树木或其他植物的生长速度。"]
```

2022-08-25 05:21 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["精灵传送门的制作类似于下界传送门，只是采用了3x3的模式。你把精灵门核心放在中间的底座上，三个微光活木将在每面墙的焦点中心，其余的是由活木制成。它需要两个魔力池，上面有自然水晶。要激活传送门，确保池子里有足够的魔力，然后用森林法杖右击传送门。这个传送门可以用来获得高级物品以换取其他物品。它确实需要魔力来维持，所以要确保有自然水晶和它附近的魔力池中的魔力不会被完
```suggestion
			description: ["精灵传送门的制作类似于下界传送门，只是采用了3x3的模式。你把精灵门核心放在中间的底座上，三个微光活木将在每面墙的焦点中心，其余的是由活木制成。它需要两个魔力池，上面有自然水晶。要激活传送门，确保池子里有足够的魔力，然后用森林法杖右击传送门核心。这个传送门可以用来获得高级物品以换取其他物品。它确实需要魔力来维持，所以要确保有自然水晶和它附近的魔力池中的魔力不会被完全耗尽。"]
```

2022-08-25 05:21 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["使用精灵玻璃制成。使用此容器制作的药水有6种用途!"]
```suggestion
			description: ["使用精灵玻璃制成。使用此容器制作的药水有6种用途！"]
```

2022-08-25 05:21 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["当你想要一个更强大的魔力发射器时。精灵魔力发射器可发射大量的魔力，而盖亚魔力发射器比之更强大。通常情况下，火花对快速传播大量魔力更有用，但当你需要强大的爆发力来实现自动化时，这些是你的首选!"]
```suggestion
			description: ["当你想要一个更强大的魔力发射器时。精灵魔力发射器可发射大量的魔力，而盖亚魔力发射器比之更强大。通常情况下，火花对快速传播大量魔力更有用，但当你需要强大的爆发力来实现自动化时，这些是你的首选！"]
```

2022-08-25 05:21 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["如果想拿起魔力池而不丢失魔力池中的魔力，你可以把它放在魔力矿车里，一次性运输大量的魔力。只需使用魔力泵从固定的魔力池中抽出魔力，就可以将你的魔力运送到你所需要的地方!"]
```suggestion
			description: ["如果想拿起魔力池而不丢失魔力池中的魔力，你可以把它放在魔力矿车里，一次性运输大量的魔力。只需使用魔力泵从固定的魔力池中抽出魔力，就可以将你的魔力运送到你所需要的地方！"]
```

2022-08-25 05:21 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["将5块活石和4块青金石摆成正方形格子图案。将泰拉凝聚板放在上面的中心位置。在它上面放上火花以获得魔力，在泰拉凝聚板上放上一个魔力钢锭、一个魔力钻石和一个魔力珍珠，最后你会得到一个泰拉钢锭!"]
```suggestion
			description: ["将5块活石和4块青金石摆成正方形格子图案。将泰拉凝聚板放在上面的中心位置。在它上面放上火花以获得魔力，在泰拉凝聚板上放上一个魔力钢锭、一个魔力钻石和一个魔力珍珠，最后你会得到一个泰拉钢锭！"]
```

2022-08-25 05:33 UTC, Cactusstudent approved these changes

2022-08-25 05:33 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["用来制作一些东西，但如果你把它放在两个铁栅栏上，就会产生烈焰人!"]
```suggestion
			description: ["用来制作一些东西，但如果你把它放在两个铁栅栏上，就会产生烈焰人！"]
```

2022-08-25 05:37 UTC, merged