[T] (quests) shop
ShaBaiTianCN/Andromeda-Automation pull request #32
Opened 2022-08-27 06:19 UTC by luo-2233

Co-authored-by: 疯子 <1161326997@qq.com>
Co-authored-by: 咸鱼啊喵丶 <74285624+XianYuAmiao@users.noreply.github.com>
Co-authored-by: Cactusstudent <97865546+Cactusstudent@users.noreply.github.com>

2022-08-27 11:17 UTC, Cactusstudent requested changes

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "原材料战利品箱"
```suggestion
			title: "粗金属战利品箱"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "蜜蜂物品战利品箱"
这翻译咋看咋奇怪，但是还不知道咋改

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			description: ["用于快速前往您的重生点！ 我在空气中挖掘岁月的痕迹 :)"]
```suggestion
			description: ["用于快速回到您的重生点！我在空气中挖掘岁月的痕迹 :)"]
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			subtitle: "1 铁币"
```suggestion
			subtitle: "1铁币"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			subtitle: "2 下界合金币"
```suggestion
			subtitle: "2下界合金币"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "遗物"
```suggestion
			title: "饰品"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			subtitle: "5 铜币"
```suggestion
			subtitle: "5铜币"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			subtitle: "1 金币"
```suggestion
			subtitle: "1金币"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			subtitle: "5 铜币"
```suggestion
			subtitle: "5铜币"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "牛排 x64"
```suggestion
			title: "牛排x64"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "牛排 x8"
```suggestion
			title: "牛排x8"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "幸运方块 x16"
```suggestion
			title: "幸运方块x16"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "Gems战利品箱"
```suggestion
			title: "宝石战利品箱"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "美丽植物战利品箱"
```suggestion
			title: "漂亮的植物战利品箱"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "铁锭 x16"
```suggestion
			title: "铁锭x16"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "钻石 x16"
```suggestion
			title: "钻石x16"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "煎饼 x32"
```suggestion
			title: "煎饼x32"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "红石块 x16"
```suggestion
			title: "红石块x16"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "巧克力板 x1"
```suggestion
			title: "巧克力板x1"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "破损的唱片 1"
```suggestion
			title: "破损的唱片x1"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "武器战利品盒"
```suggestion
			title: "武器战利品箱"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "家具战利品盒"
```suggestion
			title: "家具战利品箱"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "染料战利品盒"
```suggestion
			title: "染料战利品箱"
```

2022-08-27 11:17 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "生物资源战利品盒"
```suggestion
			title: "生物资源战利品箱"
```

2022-08-28 04:15 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "蜜蜂物品战利品箱"
```suggestion
			title: "养蜂战利品箱"
```

2022-08-28 04:16 UTC, AnzhiZhang approved these changes

2022-08-28 06:04 UTC, Cactusstudent approved these changes

2022-08-28 07:18 UTC, merged