[T] (questst) simple_storage
ShaBaiTianCN/Andromeda-Automation pull request #7
Opened 2022-08-24 01:38 UTC by luo-2233

Co-authored-by: 渊荀 <1046567763@qq.com>

2022-08-24 02:06 UTC, Cactusstudent requested changes
Machine Translation

2022-08-24 02:06 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/simple_storage.snbt
> +			description: ["一次传输大量项目。"]
```suggestion
			description: ["一次传输大量物品。"]
```

2022-08-24 02:06 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/simple_storage.snbt
> +			description: ["将堆栈大小设置为 1！"]
```suggestion
			description: ["将堆叠大小设置为 1！"]
```

2022-08-24 02:06 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/simple_storage.snbt
> +				"处理筛选器中的特定数量的项目。"
```suggestion
				"处理过滤器中的特定数量的物品。"
```

2022-08-24 02:45 UTC, AnzhiZhang approved these changes

2022-08-25 01:13 UTC, Cactusstudent approved these changes

2022-08-25 01:15 UTC, merged